name: Ash Trigger auto deployment for ash-contapp2

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ main ]
    paths:
    - '**'
    - '.github/workflows/ash-contapp2-AutoDeployTrigger-27ec6eec-0777-4697-8348-4b10d87f4c59.yml'

  # Allow manual trigger 
  workflow_dispatch:      

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions: 
      id-token: write #This is required for requesting the OIDC JWT Token
      contents: read #Required when GH token is used to authenticate with private repo

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.ASHCONTAPP2_AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.ASHCONTAPP2_AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.ASHCONTAPP2_AZURE_SUBSCRIPTION_ID }}

      - name: Build and push container image to registry
        uses: azure/container-apps-deploy-action@v2
        with:
          appSourcePath: ${{ github.workspace }}
          _dockerfilePathKey_: _dockerfilePath_
          registryUrl: ashcontainerreg.azurecr.io
          registryUsername: ${{ secrets.ASHCONTAPP2_REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.ASHCONTAPP2_REGISTRY_PASSWORD }}
          containerAppName: ash-contapp2
          resourceGroup: ash-resourcegroup
          imageToBuild: ashcontainerreg.azurecr.io/ash-contapp2:${{ github.sha }}
          _buildArgumentsKey_: |
            _buildArgumentsValues_
